code: productVisionBoard
title: Product Vision Board
summary: Roman Pichler’s unique approach to your product’s value proposition doesn’t look at it from the lens of your user but of your business.
orientation: vertical
children:
  - type: panel
    size: 20
    icon: eye
    code: VISION
    title: Vision
    summary: |
      What is your purpose of creating this product.  
      What is your purpose of creating this product. What is your purpose of creating this product.      
    datatype: text

  - type: container
    size: 40
    orientation: horizontal
    children:
      - type: panel
        size: 25
        icon: users
        code: TARGETGROUPS
        title: Target Groups
        summary: Summary of TargetGroup
        datatype: list

      - type: panel
        size: 25
        icon: heart
        code: NEEDS
        title: Needs
        summary: Summary of Needs
        datatype: list

      - type: panel
        size: 25
        icon: cube
        code: PRODUCTS
        title: Products
        summary: Summary of Products
        datatype: list

      - type: panel
        size: 25
        icon: bullseye
        code: BUSINESSGOALS
        title: Business Goals
        summary: Summary of BusinessGoals
        datatype: list

  - type: container
    size: 40
    orientation: horizontal
    children:
      - type: panel
        size: 25
        icon: users-cog
        code: COMPETITORS
        title: Competitors
        summary: Summary of Competitors
        datatype: list

      - type: panel
        size: 25
        icon: money-check-alt
        code: REVENUESTREAMS
        title: Revenue Streams
        summary: Summary of RevenueStreams
        datatype: list

      - type: panel
        size: 25
        icon: coins
        code: COSTFACTORS
        title: Cost Factors
        summary: Summary of Cost Factors
        datatype: list

      - type: panel
        size: 25
        icon: truck-moving
        code: CHANNELS
        title: Channels
        summary: Summary of Channels
        datatype: list
